### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by N00bProgrammer123** [jeottesen/win10-default-profile#1]
I like you set up but I was wondering if you had the source code to make changes via PowerShell. I would like to edit the setup to my needs so I was wondering if you could help me out by supplying the source code. Sorry for the silly question but I'm a total beginner and I'm trying to automate my setups for work. 

Thank you in advance.

**Comment by jeottesen** [comment]
Sorry for the extremely late reply. I'm not sure if you need it anymore but the source for the powershell script is located here.

[scripts/default-profile-setup.ps1](https://github.com/jeottesen/win10-default-profile/blob/d085a36a2dabf8f10d9f7c65b31d7b4c99e1f0a4/scripts/default-profile-setup.ps1)
